apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: treestore

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: treestore
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: reasoning-service

commonLabels:
  environment: production
